=== fabriziogueli/DistributedProgrammingProject/FDS-2/xsd/FDSInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/FDSInfo" targetNamespace="http://www.example.org/FDSInfo">

 <element name="FlightMonitor" type="tns:FlightMonitorType"/>

<complexType name="FlightMonitorType">
   <sequence>
    <element name="Aircraft" type="tns:AircraftType" minOccurs="0" maxOccurs="unbounded"/>
     <element name="Flight" type="tns:FlightType" minOccurs="0" maxOccurs="unbounded"/>
      <element name="FlightInstance" type="tns:FlightInstanceType" minOccurs="0" maxOccurs="unbounded"/>
   </sequence>
  </complexType>
 
 
 <complexType name="AircraftType">
  <sequence>
   <element name="Seat" type="string" minOccurs="1" maxOccurs="unbounded"/>
  </sequence>
  
  <attribute name="Model" type="ID" use="required"/>
 </complexType>
 
 
 <complexType name="FlightType">
  <attribute name="DestinationAirport" type="tns:AirportType" use="required"/>
	<attribute name="DepartureAirport" type="tns:AirportType" use="required"/>
	<attribute name="DepartureTime" type="time" use="required"/>
	<attribute name="Number" type="tns:NumberType" use="required"/>
	
 </complexType>
 
 
 <complexType name="FlightInstanceType">
  <sequence>
   <element name="Passenger" type="tns:PassengerType" minOccurs="0"  maxOccurs="unbounded" />
  </sequence>
  
  <attribute name="DepartureGate" type="string" use="required"/>
	<attribute name="Aircraft" type="IDREF" use="required"/>
	<attribute name="Flight" type="IDREF" use="required"/>
	<attribute name="Delay" type="integer" use="required"/>
	<attribute name="Date" type="date" use="required"/>
	
	<attribute name="Status" type="tns:StatusType" use="required"/>
   
 
  </complexType>
  
  
  <complexType name="PassengerType">
   <attribute name="Name" type="string" use="required"/>
    <attribute name="Seat" type="string" use="required"/>
     <attribute name="Boarded" type="boolean" use="required"/>
   
  </complexType>
  
  
  <simpleType name="NumberType">
    	<restriction base="ID">
    		<pattern value="[A-Z]{2}([0-9]){0,4}"></pattern>
    	</restriction>
    </simpleType>
    
    <simpleType name="AirportType">
    	<restriction base="string">
    		<pattern value="[A-Z]{3}"></pattern>
    	</restriction>
    </simpleType>
    
    <simpleType name="StatusType">
    	<restriction base="string">
     <enumeration value="ARRIVED"/>
     <enumeration value="BOARDING"/>
     <enumeration value="BOOKING"/>
      <enumeration value="CANCELLED"/>
       <enumeration value="CHECKINGIN"/>
        <enumeration value="DEPARTED"/>
    	</restriction>
    </simpleType>
    
</schema>

=== fabriziogueli/DistributedProgrammingProject/FDS-2/xsd/FDSInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:FlightMonitor xmlns:tns="http://www.example.org/FDSInfo"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
			xsi:schemaLocation="http://www.example.org/FDSInfo FDSInfo.xsd">
    
<Aircraft Model="BOEING-775">
    
 <Seat>1A</Seat>
 
 <Seat>1B</Seat> 
 
 <Seat>1C</Seat> 
 
 <Seat>1D</Seat> 
 
 <Seat>1E</Seat> 
 
 <Seat>1F</Seat> 
       
</Aircraft>   

<Aircraft Model="BOEING-888">
    
 <Seat>1A</Seat>
 
 <Seat>1B</Seat> 
 
 <Seat>2A</Seat> 
 
 <Seat>2B</Seat> 
 
 <Seat>3A</Seat> 
 
 <Seat>3B</Seat> 
      
</Aircraft>  
       

    
<Flight  DepartureAirport="PMO" DestinationAirport="PSA" Number="FR325"   DepartureTime="13:25:00"></Flight>   


<Flight  DepartureAirport="CTA" DestinationAirport="TRN" Number="FR200"   DepartureTime="21:00:00"></Flight> 
       

    
 <FlightInstance DepartureGate="5" Aircraft="BOEING-775" Status="CHECKINGIN" Date="2014-05-13" Flight="FR325" >
     
 <Passenger Name="Fabrizio Gueli" Seat="3A" Boarded="true"></Passenger>  
 
 <Passenger Name="Alessandro DelPiero" Seat="3B" Boarded="true"></Passenger> 
 
 <Passenger Name="Jimmy Page" Seat="2B" Boarded="false"></Passenger>    
        
 </FlightInstance>   
 
 
 
 <FlightInstance DepartureGate="10" Aircraft="BOEING-888"  Status="BOARDING" Date="2014-10-08" Flight="FR200" Delay="15"  >
     
<Passenger Name="Gianluigi Buffon" Seat="1A" Boarded="false"></Passenger>   

<Passenger Name="Andrea Pirlo" Seat="1B" Boarded="false"></Passenger>  
        
 </FlightInstance>   
        
</tns:FlightMonitor>
